import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Tab from "@/components/Tab";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <main className="min-w-full min-h-full h-screen bg-white text-black flex overflow-scroll">
        <Tab />
        <div className="flex-1 flex flex-col">
          {children}
        </div>
      </main>
      </body>
    </html>
  );
}

